INSERT INTO FINANCE.TAX (NAME,DESCRIPTION) VALUES('GST/TPS','The goods and services tax / La taxe sur les produits et services');
select @a := scope_identity();
INSERT INTO FINANCE.TAX_RATE (TAX_ID,RATE,DESCRIPTION,STARTDATE,ENDDATE) VALUES(@a,5,null,default,default);

INSERT INTO FINANCE.TAX (NAME,DESCRIPTION) VALUES('QST/TVQ','The Québec sales tax / La taxe de vente du Québec');
select @a := scope_identity();
INSERT INTO FINANCE.TAX_RATE (TAX_ID,RATE,DESCRIPTION,STARTDATE,ENDDATE) VALUES(@a,9.5,null,'2015-06-01 00:00:00',default);

INSERT INTO FINANCE.ORGANIZATION (NAME,DESCRIPTION) VALUES('job','my job');
INSERT INTO FINANCE.ORGANIZATION (NAME,DESCRIPTION) VALUES('walmart','shop');
INSERT INTO FINANCE.ORGANIZATION (NAME,DESCRIPTION) VALUES('rbc','bank');
INSERT INTO FINANCE.ORGANIZATION (NAME,DESCRIPTION) VALUES('sami fruits','shop');

INSERT INTO FINANCE.CURRENCY (CODE, NAME, DESCRIPTION) VALUES('CAD','canadian dollar','canadian dollar desc');
INSERT INTO FINANCE.CURRENCY (CODE, NAME, DESCRIPTION) VALUES('USD ','american dollar','american dollar desc');
INSERT INTO FINANCE.CURRENCY (CODE, NAME, DESCRIPTION) VALUES('MDL ','moldavian lei','moldavian lei desc');

INSERT INTO FINANCE.ACCOUNT_GROUP (NAME, DESCRIPTION) VALUES('cash','money in wallet');
INSERT INTO FINANCE.ACCOUNT_GROUP (NAME, DESCRIPTION) VALUES('credit card','credit cards');

INSERT INTO FINANCE.ACCOUNT (NAME, DESCRIPTION, ACCOUNT_GROUP_ID, CURRENCY_ID, INITIAL_BALANCE) VALUES('cash CAD','money in wallet cad',1,1, 100);
INSERT INTO FINANCE.ACCOUNT (NAME, DESCRIPTION, ACCOUNT_GROUP_ID, CURRENCY_ID, INITIAL_BALANCE) VALUES('cash USD','money in wallet usd',1,2, 100);
INSERT INTO FINANCE.ACCOUNT (NAME, DESCRIPTION, ACCOUNT_GROUP_ID, CURRENCY_ID, INITIAL_BALANCE) VALUES('visa 1234 CAD','credit card initial balance is a limit',2,1, 500);

INSERT INTO FINANCE.INVOICE (ACCOUNT_ID,ORGANIZATION_ID,CURRENCY_ID,DATE,COMMENT) VALUES(1,1,1,'2016-02-11','SALARY');
INSERT INTO FINANCE.ITEM (DESCRIPTION1,DESCRIPTION2,INVOICE_ID,AMOUNT,) VALUES('ЗП','SALARY',1,1000);