--balance per account
SELECT A.ID,A.NAME,A.ACCOUNT_GROUP_TYPE,SUM(T.DEBIT_AMOUNT) ,SUM(T.CREDIT_AMOUNT),SUM(T.DEBIT_AMOUNT)-SUM(T.CREDIT_AMOUNT) BALANCE FROM FINANCE.TRANSACTION T join FINANCE.ACCOUNT A ON T.ACCOUNT_ID = A.ID GROUP BY T.ACCOUNT_ID
--reverse: calculate with credit/debit in mind
SELECT A.ID,A.NAME,A.ACCOUNT_GROUP_TYPE,SUM(T.DEBIT_AMOUNT) ,SUM(T.CREDIT_AMOUNT),
    CASEWHEN(A.ACCOUNT_GROUP_TYPE='D',
        SUM(T.DEBIT_AMOUNT)-SUM(T.CREDIT_AMOUNT),
        CASEWHEN(A.ACCOUNT_GROUP_TYPE='C',SUM(T.CREDIT_AMOUNT)-SUM(T.DEBIT_AMOUNT), 'not supported')) BALANCE
FROM FINANCE.TRANSACTION T join FINANCE.ACCOUNT A ON T.ACCOUNT_ID = A.ID GROUP BY T.ACCOUNT_ID

--account balance per day (no accumulating)
SELECT T.DATE,A.ID,A.NAME ,SUM(T.DEBIT_AMOUNT) ,SUM(T.CREDIT_AMOUNT),SUM(T.DEBIT_AMOUNT)-SUM(T.CREDIT_AMOUNT) BALANCE FROM FINANCE.TRANSACTION T join FINANCE.ACCOUNT A ON T.ACCOUNT_ID = A.ID GROUP BY T.DATE,T.ACCOUNT_ID ORDER BY T.DATE,T.ACCOUNT_ID


SELECT C.ID,C.CODE,C.NAME,A.ID,A.NAME ,SUM(T.DEBIT_AMOUNT) ,SUM(T.CREDIT_AMOUNT),SUM(T.DEBIT_AMOUNT)-SUM(T.CREDIT_AMOUNT) BALANCE FROM FINANCE.CURRENCY C JOIN FINANCE.ACCOUNT A ON A.CURRENCY_ID = C.ID JOIN FINANCE.TRANSACTION T ON T.ACCOUNT_ID = A.ID GROUP BY C.ID,A.ID