--create sequence group_seq;
--create table test3(id bigint default group_seq.nextval primary key);
--And if not:
--create table test1(id identity);
--or
--create table test2(id bigint auto_increment primary key);

--http://blog.sqlauthority.com/2009/09/07/sql-server-importance-of-database-schemas-in-sql-server/
CREATE SCHEMA FINANCE;


--http://www.revenuquebec.ca/fr/entreprises/taxes/tpstvhtvq/reglesdebase/historiquetauxtpstvq.aspx
--https://fr.wikipedia.org/wiki/Taxe_de_vente_du_Qu%C3%A9bec
CREATE TABLE FINANCE.TAX(
ID identity,
NAME VARCHAR(100),
DESCRIPTION VARCHAR(512),
FORMULA VARCHAR(512)
);

--load tax in a context class when app is starting to avoid query this table everytime
--put a listener in UI part if tax rate is changed then update in config file
--2 types of app: general and specific for Canada
CREATE TABLE FINANCE.TAX_RATE(
ID identity,
TAX_ID BIGINT,
RATE DECIMAL(20,2) DEFAULT 0.00,
DESCRIPTION VARCHAR(512),
STARTDATE TIMESTAMP DEFAULT '1970-01-01 00:00:00',
ENDDATE TIMESTAMP DEFAULT '2037-01-01 00:00:00',
FOREIGN KEY (TAX_ID) REFERENCES TAX(ID),
);

CREATE TABLE FINANCE.ORGANIZATION(
ID identity,
NAME VARCHAR(65),
DESCRIPTION VARCHAR(1024),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
T_CREATEDBY VARCHAR(512),
T_UPDATEDBY VARCHAR(512)
);

CREATE TABLE FINANCE.CURRENCY(
ID identity,
CODE VARCHAR(12),
NAME VARCHAR(65),
DESCRIPTION VARCHAR(1024),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
T_CREATEDBY VARCHAR(512),
T_UPDATEDBY VARCHAR(512)
);


CREATE TABLE FINANCE.ACCOUNT_GROUP(
ID identity,
NAME VARCHAR(65),
DESCRIPTION VARCHAR(1024),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
T_CREATEDBY VARCHAR(512),
T_UPDATEDBY VARCHAR(512)
);

CREATE TABLE FINANCE.ACCOUNT(
ID identity,
ACCOUNT_GROUP_ID BIGINT,
CURRENCY_ID BIGINT,
NAME VARCHAR(65),
DESCRIPTION VARCHAR(1024),
INITIAL_BALANCE DECIMAL(20,6) DEFAULT 0.00,
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
T_CREATEDBY VARCHAR(512),
T_UPDATEDBY VARCHAR(512),
FOREIGN KEY (ACCOUNT_GROUP_ID) REFERENCES ACCOUNT_GROUP(ID),
FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(ID)
);

CREATE TABLE FINANCE.INVOICE(
ID identity,
ACCOUNT_ID BIGINT,
ORGANIZATION_ID BIGINT,
CURRENCY_ID BIGINT,
DATE DATE NOT NULL,
COMMENT VARCHAR(512),
CUSTOM1 DECIMAL(20,6) DEFAULT 0.00,
CUSTOM2 DECIMAL(20,6) DEFAULT 0.00,
BALANCE DECIMAL(20,6) DEFAULT 0.00,
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
T_CREATEDBY VARCHAR(512),
T_UPDATEDBY VARCHAR(512),
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID)
FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(ID)
);

CREATE TABLE FINANCE.ITEM(
ID identity,
DESCRIPTION1 VARCHAR(512),
DESCRIPTION2 VARCHAR(512),
INVOICE_ID BIGINT,
AMOUNT DECIMAL(20,6) DEFAULT 0.00,
TAX_ID BIGINT,
COMMENT VARCHAR(512),
FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(ID),
FOREIGN KEY (TAX_ID) REFERENCES TAX(ID)
);

--EXAMPLE
--http://stackoverflow.com/questions/29993308/h2-how-to-create-a-database-trigger-that-log-a-row-change-to-another-table
--CREATE TRIGGER TRANSACTION_SUM_T
--AFTER INSERT
--ON ITEM
--FOR EACH ROW
--CALL "com.example.MyTrigger"

